// Code generated by "stringer -type=enum"; DO NOT EDIT.

package finitestatemachine_test

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS_IDLE-1]
	_ = x[STATUS_READY-2]
	_ = x[ACTION_STARTUP - -1]
	_ = x[ACTION_SHUTDOWN - -2]
}

const (
	_enum_name_0 = "ACTION_SHUTDOWNACTION_STARTUP"
	_enum_name_1 = "STATUS_IDLESTATUS_READY"
)

var (
	_enum_index_0 = [...]uint8{0, 15, 29}
	_enum_index_1 = [...]uint8{0, 11, 23}
)

func (i enum) String() string {
	switch {
	case -2 <= i && i <= -1:
		i -= -2
		return _enum_name_0[_enum_index_0[i]:_enum_index_0[i+1]]
	case 1 <= i && i <= 2:
		i -= 1
		return _enum_name_1[_enum_index_1[i]:_enum_index_1[i+1]]
	default:
		return "enum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
