#!/bin/sh
set -e

injectEmbed(){
	[ -z "$1" ] && return 0;
	local F="$1"; shift;
	local V=$(echo $F | tr '.' '_');
	echo "\n\t//go:embed ${F}\n\t${V} string";
	injectEmbed $@;
};

injectFunc(){
	[ -z "$1" ] && return 0;
	local F="$1"; shift;
	local V=$(echo $F | tr '.' '_');
	local N=$(echo $V | tr '[:lower:]' '[:upper:]');
	local C=$(cat $F);
	echo "\n/* ${F}\n${C}*/"
	echo "func ${N}() string { return ${V} }"
	injectFunc $@;
}

cat << EOF > ./query.gen.go
//go:generate $0

// Package query
// 
// Code generated by $0 DO NOT EDIT.
package query

import "embed"

type NoScan struct{}

func (NoScan) Scan(any) error { return nil }

var (
	_ embed.FS
$(injectEmbed $(ls -1 *.sql))
)
$(injectFunc $(ls -1 *.sql))
EOF
