//go:generate ./query.gen.sh

// Package query
// 
// Code generated by ./query.gen.sh DO NOT EDIT.
package query

import "embed"

type NoScan struct{}

func (NoScan) Scan(any) error { return nil }

var (
	_ embed.FS

	//go:embed sqlite3.authn.migration.sql
	sqlite3_authn_migration_sql string

	//go:embed sqlite3.authn.mutation.account_insert.sql
	sqlite3_authn_mutation_account_insert_sql string

	//go:embed sqlite3.authn.mutation.account_update.sql
	sqlite3_authn_mutation_account_update_sql string

	//go:embed sqlite3.authn.query.account_lookup.sql
	sqlite3_authn_query_account_lookup_sql string
)

/* sqlite3.authn.migration.sql
    CREATE TABLE IF NOT EXISTS accounts (
        _id            BLOB NOT NULL PRIMARY KEY,-- server generated ID
        _username      TEXT NOT NULL UNIQUE,     -- username
        _key_id        BLOB NOT NULL,            -- server owned key ID to operate with encrypted value
        _password      BLOB NOT NULL,            -- hashed + encrypted
        _passwordless  BLOB     NULL,            -- encrypted token contains
        _totp_secret   BLOB     NULL,            -- encrypted
        _totp_recovery BLOB     NULL,            -- hashed + encrypted
        _email_address BLOB     NULL,            -- hashed
        _phone_number  BLOB     NULL,            -- hashed
        _update_key    BLOB NOT NULL,            -- needed in update query
        _updated_at    INT  NOT NULL)            -- last update (unix time in seconds)
    WITHOUT ROWID, STRICT;

    CREATE TABLE IF NOT EXISTS account_attributes (
        _id         BLOB NOT NULL PRIMARY KEY,-- server generated ID
        _account_id BLOB NOT NULL,            -- FK to `accounts`._id
        _type       INT  NOT NULL,            -- reflected as enum on server side
        _key_id     BLOB     NULL,            -- server owned key ID to operate with encrypted value
        _ciphertext BLOB     NULL,            -- encrypted value
        _plaintext  BLOB     NULL,            -- unencrypted value
        _started_at INT  NOT NULL,            -- recorded time of attribute to start
        _expired_at INT  NOT NULL,            -- recorded time of attribute to end - there would be daemon to delete all expired records
        _updated_at INT  NOT NULL)            -- recorded time of last update (unix time in seconds)
    WITHOUT ROWID, STRICT;*/
func SQLITE3_AUTHN_MIGRATION_SQL() string { return sqlite3_authn_migration_sql }

/* sqlite3.authn.mutation.account_insert.sql
    INSERT INTO accounts (
        _id, _username, _key_id, _password, _passwordless, _totp_secret, _totp_recovery, _email_address, _phone_number, _update_key, _updated_at
    ) SELECT
        CAST(@id AS BLOB),
        CAST(@username AS TEXT),
        CAST(@key_id AS BLOB),
        CAST(@password AS BLOB),
        CAST(@passwordless AS BLOB),
        CAST(@totp_secret AS BLOB),
        CAST(@totp_recovery AS BLOB),
        CAST(@email_address AS BLOB),
        CAST(@phone_number AS BLOB),
        CAST(@update_key AS BLOB),
        CAST(@updated_at AS INT)
    WHERE @id       NOT IN (SELECT _id FROM accounts)
    AND   @username NOT IN (SELECT _username FROM accounts)
    ;*/
func SQLITE3_AUTHN_MUTATION_ACCOUNT_INSERT_SQL() string { return sqlite3_authn_mutation_account_insert_sql }

/* sqlite3.authn.mutation.account_update.sql
    UPDATE accounts SET
        _username       = IFNULL(CAST(@username AS TEXT),      _username),
        _key_id         = IFNULL(CAST(@key_id AS BLOB),        _key_id),
        _password       = IFNULL(CAST(@password AS BLOB),      _password),
        _passwordless   = IFNULL(CAST(@passwordless AS BLOB),  _passwordless),
        _totp_secret    = IFNULL(CAST(@totp_secret AS BLOB),   _totp_secret),
        _totp_recovery  = IFNULL(CAST(@totp_recovery AS BLOB), _totp_recovery),
        _email_address  = IFNULL(CAST(@email_address AS BLOB), _email_address),
        _phone_number   = IFNULL(CAST(@phone_number AS BLOB),  _phone_number),
        _update_key     = CAST(@update_key AS BLOB),
        _updated_at     = CAST(@updated_at AS INT)
    WHERE   CAST(@id AS BLOB) = _id
        AND CAST(@last_update_key AS BLOB) = _update_key
        AND CAST(@last_update_key AS BLOB) <> CAST(@update_key AS BLOB)
        AND CAST(@last_update_key AS BLOB) IS NOT NULL
        AND CAST(@update_key AS BLOB) IS NOT NULL
        AND CAST(@updated_at AS INT) > _updated_at
    ;*/
func SQLITE3_AUTHN_MUTATION_ACCOUNT_UPDATE_SQL() string { return sqlite3_authn_mutation_account_update_sql }

/* sqlite3.authn.query.account_lookup.sql
    SELECT
        _id,
        _username,
        _key_id,
        _password,
        _passwordless,
        _totp_secret,
        _totp_recovery,
        _email_address,
        _phone_number,
        _update_key,
        _updated_at
    FROM accounts
    WHERE  _id = @id
        OR _username = @username OR _username = @lookup
        OR _email_address = @email_address OR _email_address = @lookup
        OR _phone_number = @phone_number OR _phone_number = @lookup
        OR _key_id = @key_id*/
func SQLITE3_AUTHN_QUERY_ACCOUNT_LOOKUP_SQL() string { return sqlite3_authn_query_account_lookup_sql }
